export const fallbackFaculties = [
  {
    id: 1,
    name: 'Fakultas Teknologi Informasi',
    code: 'FTI',
    slug: 'fti',
    tagline: 'Leading the Future with Artificial Intelligence & Cyber Security',
    description: 'Fakultas pelopor komputasi di Indonesia sejak 1979 dengan konsentrasi kecerdasan buatan, keamanan siber, data science, dan rekayasa perangkat lunak.',
    deanName: 'Dr. Ir. Deni Mahdiana, S.Kom., M.M., M.Kom.',
    deanTitle: 'Dekan Fakultas Teknologi Informasi',
    deanImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop',
    colorAccent: '#1ca3dc',
    studyPrograms: [
      {
        id: 1,
        facultyId: 1,
        name: 'Teknik Informatika',
        degree: 'S1',
        slug: 'teknik-informatika-s1',
        accreditation: 'Unggul',
        description: 'Fokus pada AI, Machine Learning, Cloud Computing, dan Rekayasa Perangkat Lunak tingkat lanjut.',
        careerProspects: 'AI Engineer, Software Architect, Fullstack Developer, Data Scientist',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 6.500.000',
        bannerImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop',
        isPopular: true,
      },
      {
        id: 2,
        facultyId: 1,
        name: 'Sistem Informasi',
        degree: 'S1',
        slug: 'sistem-informasi-s1',
        accreditation: 'Unggul',
        description: 'Integrasi teknologi informasi dengan strategi bisnis digital, enterprise ERP, dan business analytics.',
        careerProspects: 'IT Consultant, Business Analyst, Product Manager, ERP Specialist',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 6.300.000',
        bannerImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
        isPopular: true,
      },
      {
        id: 3,
        facultyId: 1,
        name: 'Sistem Komputer (IoT & Cyber)',
        degree: 'S1',
        slug: 'sistem-komputer-s1',
        accreditation: 'Unggul',
        description: 'Pengembangan perangkat embedded, robotika, Internet of Things, dan pertahanan siber jaringan.',
        careerProspects: 'IoT Engineer, Cyber Security Analyst, Hardware Developer',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 6.200.000',
        bannerImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop',
        isPopular: false,
      },
    ],
  },
  {
    id: 2,
    name: 'Fakultas Ekonomi & Bisnis',
    code: 'FEB',
    slug: 'feb',
    tagline: 'Empowering Sustainable Global Business & FinTech Leaders',
    description: 'Mencetak pemimpin bisnis, akuntan profesional, dan wirausahawan beretika luhur yang adaptif terhadap transformasi ekonomi digital.',
    deanName: 'Dr. Dra. Sunarmi, M.M.',
    deanTitle: 'Dekan Fakultas Ekonomi & Bisnis',
    deanImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&auto=format&fit=crop',
    colorAccent: '#fced17',
    studyPrograms: [
      {
        id: 4,
        facultyId: 2,
        name: 'Manajemen (Digital & Finance)',
        degree: 'S1',
        slug: 'manajemen-s1',
        accreditation: 'Unggul',
        description: 'Mempersiapkan manajer global dan technopreneur dengan konsentrasi Digital Marketing, FinTech, dan HRM.',
        careerProspects: 'Business Developer, Marketing Strategist, Financial Manager, Entrepreneur',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 5.900.000',
        bannerImage: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop',
        isPopular: true,
      },
      {
        id: 5,
        facultyId: 2,
        name: 'Akuntansi & Perpajakan',
        degree: 'S1',
        slug: 'akuntansi-s1',
        accreditation: 'Unggul',
        description: 'Keahlian audit forensik, akuntansi keberlanjutan (ESG), perpajakan digital, dan sistem informasi akuntansi.',
        careerProspects: 'Auditor, Tax Consultant, Financial Controller, Forensic Accountant',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 5.900.000',
        bannerImage: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop',
        isPopular: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Fakultas Komunikasi & Desain Kreatif',
    code: 'FKDK',
    slug: 'fkdk',
    tagline: 'Inspiring Creative Culture, Digital Media & Visual Art',
    description: 'Pusat produksi konten visual, broadcasting TV, periklanan kreatif, dan desain grafis masa depan dengan fasilitas studio televisi mandiri.',
    deanName: 'Bona Sardo, M.Si.',
    deanTitle: 'Dekan Fakultas Komunikasi & Desain Kreatif',
    deanImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&auto=format&fit=crop',
    colorAccent: '#de1f26',
    studyPrograms: [
      {
        id: 6,
        facultyId: 3,
        name: 'Ilmu Komunikasi (Broadcasting & PR)',
        degree: 'S1',
        slug: 'ilmu-komunikasi-s1',
        accreditation: 'Unggul',
        description: 'Produksi program TV profesional, jurnalisme investigatif, Corporate PR, dan Strategic Social Media.',
        careerProspects: 'TV Producer, News Anchor, Public Relations Specialist, Content Director',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 6.100.000',
        bannerImage: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800&auto=format&fit=crop',
        isPopular: true,
      },
      {
        id: 7,
        facultyId: 3,
        name: 'Desain Komunikasi Visual (DKV)',
        degree: 'S1',
        slug: 'dkv-s1',
        accreditation: 'Unggul',
        description: 'Perancangan branding identitas, animasi 3D, UI/UX interaction design, dan ilustrasi digital kontemporer.',
        careerProspects: 'UI/UX Designer, Creative Director, 3D Animator, Brand Strategist',
        totalCredits: 144,
        tuitionPerSemester: 'Rp 6.200.000',
        bannerImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&auto=format&fit=crop',
        isPopular: true,
      },
    ],
  },
];

export const fallbackNews = [
  {
    id: 1,
    title: 'Universitas Budi Luhur Raih Akreditasi UNGGUL BAN-PT 2024-2029',
    slug: 'ubl-raih-akreditasi-unggul-ban-pt',
    category: 'Akademik',
    summary: 'Pencapaian bersejarah akreditasi tertinggi BAN-PT membuktikan komitmen mutu pendidikan berkarakter dan berstandar internasional.',
    content: 'Universitas Budi Luhur resmi memperoleh status Akreditasi UNGGUL dari Badan Akreditasi Nasional Perguruan Tinggi (BAN-PT). Capaian ini merupakan buah kerja keras seluruh sivitas akademika dalam menjaga mutu tridharma perguruan tinggi berlandaskan nilai-nilai luhur kebudiluhuran.',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop',
    author: 'Humas Budi Luhur',
    views: 1420,
    publishedAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'Mobil Reli Listrik BLITS Sukses Tempuh Ekspedisi Keliling Nusantara 15.000 KM',
    slug: 'blits-sukses-keliling-nusantara',
    category: 'Riset & Inovasi',
    summary: 'Inovasi mobil listrik buatan sivitas akademika UBL mencatatkan rekor ketahanan baterai dan medan off-road di Indonesia.',
    content: 'Mobil listrik BLITS buatan tim riset Universitas Budi Luhur bersama ITS sukses menuntaskan uji coba penjelajahan keliling Indonesia sejauh 15.000 KM tanpa kendala teknis berarti, membuktikan kesiapan teknologi kendaraan listrik karya anak bangsa.',
    imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop',
    author: 'Pusat Riset EV UBL',
    views: 2150,
    publishedAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'Mahasiswa FTI Budi Luhur Juara 1 AI Hackathon Nasional 2025',
    slug: 'mahasiswa-fti-juara-ai-hackathon-2025',
    category: 'Prestasi Mahasiswa',
    summary: 'Solusi kecerdasan buatan untuk deteksi dini penyakit tanaman pangan berhasil mengalahkan puluhan perguruan tinggi ternama.',
    content: 'Tim mahasiswa Fakultas Teknologi Informasi UBL berhasil meraih Juara 1 pada ajang National AI Hackathon dengan inovasi sistem computer vision cerdas untuk membantu ketahanan pangan nasional.',
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&auto=format&fit=crop',
    author: 'Biro Kemahasiswaan',
    views: 980,
    publishedAt: new Date().toISOString(),
  },
];

export const fallbackEvents = [
  {
    id: 1,
    title: 'Budi Luhur Career & Tech Fair 2026',
    slug: 'career-tech-fair-2026',
    date: '15 - 17 September 2026',
    time: '09:00 - 16:00 WIB',
    location: 'Auditorium Grha Budi Luhur',
    organizer: 'Biro Karir & Alumni',
    category: 'Career Fair',
    description: 'Bursa kerja dan pameran teknologi menghadirkan lebih dari 60 perusahaan multinasional dan startup terkemuka.',
  },
  {
    id: 2,
    title: 'Seminar Nasional AI & Electric Vehicles Conference (AIEV 2026)',
    slug: 'aiev-conference-2026',
    date: '28 Oktober 2026',
    time: '08:30 - 15:00 WIB',
    location: 'Ballroom Lt. 3 Kampus Pusat',
    organizer: 'Lembaga Riset & Pengabdian Masyarakat',
    category: 'Konferensi',
    description: 'Pertemuan pakar teknologi energi baru terbarukan dan artificial intelligence dari 5 negara mitra.',
  },
  {
    id: 3,
    title: 'Open House & Workshop Kreatif PMB 2026',
    slug: 'open-house-pmb-2026',
    date: '10 November 2026',
    time: '10:00 - 14:00 WIB',
    location: 'Studio BLTV & Lab Multimedia',
    organizer: 'Tim Admisi & PMB',
    category: 'Workshop',
    description: 'Trial class gratis broadcasting, coding, dan UI/UX design untuk siswa kelas 12 SMA/SMK.',
  },
];

export const fallbackInnovations = [
  {
    id: 1,
    name: 'BLITS (Budi Luhur - ITS Electric Rally Car)',
    slug: 'blits-electric-car',
    category: 'Electric Vehicle',
    description: 'Mobil reli bertenaga listrik 100% pertama di Indonesia yang berhasil menyelesaikan ekspedisi keliling Nusantara sejauh 15.000 KM serta uji medan Rally Dakar.',
    specs: 'Motor Listrik 50 kW, Baterai LiFePO4 100 kWh, Jarak Tempuh 300 KM / Charge, Top Speed 140 km/jam',
    imageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format&fit=crop',
    achievement: 'Rekor MURI Jelajah Nusantara 15.000 KM Mobil Listrik Nasional',
  },
  {
    id: 2,
    name: 'BLSEV-01 Sport Electric Motorcycle',
    slug: 'blsev-01-sport-motorcycle',
    category: 'Electric Vehicle',
    description: 'Motor sport balap listrik berkecepatan tinggi rancangan sivitas akademika Budi Luhur yang diuji coba secara ketat di Sirkuit Internasional Sentul.',
    specs: 'BLDC Motor 96V, Baterai 3000 Watt, Kecepatan Maksimum 160 km/jam, Sistem Pendingin Ganda',
    imageUrl: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop',
    achievement: 'Juara Kategori Desain Sirkuit Sentul & Pameran IIMS',
  },
  {
    id: 3,
    name: 'Waste-to-Energy & Bank Sampah Budi Luhur',
    slug: 'waste-to-energy-system',
    category: 'Green Technology',
    description: 'Sistem pengolahan limbah organik dan plastik mandiri kampus yang dikonversi menjadi paving block ramah lingkungan dan energi biomassa terbarukan.',
    specs: 'Kapasitas 2 Ton/Hari, Konversi Plastik HDPE/PET, Sensor IoT Timbangan Digital',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&auto=format&fit=crop',
    achievement: 'Penghargaan UI GreenMetric Top Sustainable Campus',
  },
  {
    id: 4,
    name: 'BL-Drone Agro Monitoring System',
    slug: 'bl-drone-agro',
    category: 'Robotics & AI',
    description: 'Drone pemetaan pertanian presisi bertenaga baterai cerdas dengan sensor multispektral untuk memantau kesehatan tanaman dan lahan perkebunan.',
    specs: 'Hexacopter Carbon Fiber, AI Thermal & NDVI Camera, Flight Time 45 Min',
    imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop',
    achievement: 'Hibah Riset Diktisaintek Kemendikbudristek Berdampak',
  },
];

export const fallbackFacilities = [
  {
    id: 1,
    name: 'Studio Siaran Televisi (BLTV)',
    category: 'Laboratorium',
    description: 'Studio televisi standar industri dengan 4K multi-camera, switcher triCaster, teleprompter, dan ruang kendali siaran langsung.',
    location: 'Gedung Unit 7 Lt. 3',
    imageUrl: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=800&auto=format&fit=crop',
  },
  {
    id: 2,
    name: 'Auditorium Grha Budi Luhur',
    category: 'Area Komunal',
    description: 'Gedung pertemuan megah berkapasitas 2.500 kursi dilengkapi sound system line-array konser, tata lampu panggung, dan AC central.',
    location: 'Grha Budi Luhur',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop',
  },
  {
    id: 3,
    name: 'Artificial Intelligence & Mac Lab',
    category: 'Laboratorium',
    description: 'Laboratorium komputasi performa tinggi dengan workstation GPU NVIDIA RTX dan Apple iMac untuk riset AI dan animasi digital.',
    location: 'Gedung Unit 6 Lt. 4',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop',
  },
  {
    id: 4,
    name: 'Pusat Riset Kendaraan Listrik (EV Center)',
    category: 'Laboratorium',
    description: 'Bengkel riset mekanik dan elektrik otomotif tempat perakitan mobil BLITS, motor BLSEV, dan stasiun pengisian baterai solar.',
    location: 'Workshop Teknik Kampus Barat',
    imageUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=800&auto=format&fit=crop',
  },
  {
    id: 5,
    name: 'Perpustakaan Digital & Co-Working Space',
    category: 'Akademik',
    description: 'Ruang baca asri berpendingin udara dengan akses ke jutaan e-journal internasional (IEEE, Scopus), booth riset mandiri, dan cafe corner.',
    location: 'Gedung Unit 3 Lt. 2',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop',
  },
  {
    id: 6,
    name: 'Sport Center & Lapangan Futsal Internasional',
    category: 'Olahraga & Seni',
    description: 'Fasilitas olahraga terpadu: lapangan basket vinyl FIBA, futsal interlock, climbing wall, dan pusat kebugaran mahasiswa.',
    location: 'Area Olahraga Kampus Selatan',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop',
  },
];

export const fallbackBranches = [
  {
    id: 1,
    name: 'Kampus Pusat Budi Luhur (Petukangan)',
    city: 'Jakarta Selatan',
    address: 'Jl. Ciledug Raya, Petukangan Utara, Pesanggrahan, Jakarta Selatan 12260',
    phone: '(021) 5853753',
    email: 'info@budiluhur.ac.id',
    googleMapsUrl: 'https://maps.app.goo.gl/yaFw9h4AGJN2ypiz5',
    isMainCampus: true,
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop',
  },
  {
    id: 2,
    name: 'Kampus Roxy Budi Luhur (Pusat Bisnis)',
    city: 'Jakarta Pusat',
    address: 'Komp. Roxy Mas Blok E.2 No. 5-7, Jl. KH. Hasyim Ashari, Jakarta Pusat 10150',
    phone: '(021) 6328731',
    email: 'roxy@budiluhur.ac.id',
    googleMapsUrl: 'https://maps.google.com/?q=Roxy+Mas+Jakarta',
    isMainCampus: false,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop',
  },
  {
    id: 3,
    name: 'Kampus Salemba Budi Luhur (Pascasarjana)',
    city: 'Jakarta Pusat',
    address: 'Jl. Salemba Raya No. 12, Senen, Jakarta Pusat 10430',
    phone: '(021) 3902345',
    email: 'salemba@budiluhur.ac.id',
    googleMapsUrl: 'https://maps.google.com/?q=Salemba+Raya+Jakarta',
    isMainCampus: false,
    imageUrl: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop',
  },
];
